name: Linux CI coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: grumpycoders/pcsx-redux-build:latest
      env:
        TEST_RESULTS: /tmp/test-results
        BUILD: Coverage
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          set-safe-directory: true
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          make -j 2 all pcsx-redux-tests
          make -C src/mips/openbios -j 2
          cp src/mips/openbios/openbios.bin .
          make -C src/mips/openbios clean
          make -C src/mips/tests -j 2 PCSX_TESTS=true
          cp ./openbios.bin src/mips/openbios/
      - name: Test
        run: |
          xvfb-run catchsegv ./pcsx-redux-tests
      - name: Produce code coverage
        run: |
          lcov --directory . --capture --output-file coverage.info
      - uses: codecov/codecov-action@v2
